# Exploratory Data Analysis using Transaction Data from Online Casino Players

Data Set - https://data.mendeley.com/datasets/9j5gcygnwg/1

Reference Article - https://www.sciencedirect.com/science/article/pii/S2352340923001956

In [21]:
#Data
import pandas as pd
import numpy as np
pd.options.mode.chained_assignment = None
from datetime import datetime as date

#visualization
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go

#preprocessing
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [22]:
casino = pd.read_csv('datasets/Online_casino_DIB.csv')
casino.head()

,ReqTimeUTC,TransactionType,TransactionAmount,Status,AccountIdentifier
0,2019-07-05T05:02:28+0000,LOYALTYCARDDEBIT,10.0,APPROVED,customer1734
1,2019-07-05T05:26:00+0000,LOYALTYCARDDEBIT,10.0,APPROVED,customer1734
2,2019-07-05T04:54:35+0000,LOYALTYCARDCREDITCL,10.0,APPROVED,customer1734
3,2019-07-05T05:02:27+0000,LOYALTYCARDCREDITCL,10.0,APPROVED,customer1734
4,2019-07-05T05:25:59+0000,LOYALTYCARDCREDITCL,10.0,APPROVED,customer1734

In [23]:
casino.dtypes

ReqTimeUTC               str
TransactionType          str
TransactionAmount    float64
Status                   str
AccountIdentifier        str
dtype: object

In [24]:
casino.ReqTimeUTC = pd.to_datetime(casino.ReqTimeUTC)

In [25]:
casino.describe(exclude = 'float64')

,ReqTimeUTC,TransactionType,Status,AccountIdentifier
count,138928,138928,138928,138928
unique,NaN,3,2,2361
top,NaN,LOYALTYCARDDEBIT,APPROVED,customer10
freq,NaN,70329,133520,2318
mean,2019-08-23 14:37:01.511898+00:00,NaN,NaN,NaN
min,2019-03-01 08:03:23+00:00,NaN,NaN,NaN
25%,2019-05-19 06:27:26.250000+00:00,NaN,NaN,NaN
50%,2019-08-21 13:32:02.500000+00:00,NaN,NaN,NaN
75%,2019-11-23 20:28:33.500000+00:00,NaN,NaN,NaN
max,2020-03-02 07:47:06+00:00,NaN,NaN,NaN

Since we want to limit the list of transaction we get to the beofre 2020-02-29

In [ ]:
casino = casino[casino.ReqTimeUTC < '2020-02-29 00:00:00+00:00'].copy()
casino.describe(exclude = 'float64')

,ReqTimeUTC,TransactionType,Status,AccountIdentifier
count,1071,1071,1071,1071
unique,NaN,3,2,141
top,NaN,LOYALTYCARDDEBIT,APPROVED,customer2
freq,NaN,534,1047,52
mean,2020-03-01 02:51:30.064425+00:00,NaN,NaN,NaN
min,2020-02-29 00:17:49+00:00,NaN,NaN,NaN
25%,2020-02-29 10:34:51+00:00,NaN,NaN,NaN
50%,2020-03-01 04:42:45+00:00,NaN,NaN,NaN
75%,2020-03-01 16:00:10.500000+00:00,NaN,NaN,NaN
max,2020-03-02 07:47:06+00:00,NaN,NaN,NaN